---
documentclass: uothesisapa
classoption: dissertation, copyright, draftcopy
biblatex-load-options: "backend=biber,style=apa,useprefix=false,sorting=nyt"
biblatex-print-options: "title=REFERENCES CITED,heading=bibintoc"
title: "Adolescent social motives: measurement and implications" #for pdf meta-data
author: "John C. Flournoy" #for pdf meta-data
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: "preamble.tex"
    template: "default-1.17.0.2_notitling.tex"
    citation_package: "biblatex"
    keep_tex: yes
bibliography: "dissertation.bib"
---

```{r global_options, include=FALSE}
## This saves you from having to do this for every chunk
knitr::opts_chunk$set(fig.path = 'figures/',
                      echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)

#This is where you set all of the information that will be printed. The title
#and the author in the YAML above is just for PDF metadata
dissertateUO::preamble_for_title(
  covertitle = 'Adolescent social motives: measurement and implications',
  abstracttitle = 'Adolescent social motives: measurement and implications',
  author = 'John C. Flournoy',
  department = 'Department of Psychology',
  narrowdepartment = 'Department of Psychology',
  degreetype = 'Master of Philosophy',
  degreemonth = 'August',
  degreeyear = '2018',
  chair = 'Jennifer Pfeifer',
  committee = 'Sanjay Srivastava    & Core Member \\\\
           Elliot Berkman    & Core Member \\\\
           Nicole Giuliani & Institutional Representative \\\\',
  graddean = 'Sara Hodges',
  abstract_tex = 'abstract.tex',
  cv_tex = 'cv.tex',
  acknowledge_tex = 'acknowledgements.tex',
  dedication_tex = 'dedication.tex')
```

<!-- Begin Document -->

<!-- Introduction -->

\chapter{Introduction}

```{r child='introduction.Rmd'}
```

\FloatBarrier

<!-- Chapter 2 -->
\chapter{Methodology}

```{r child='ch02_descriptives.Rmd'}
```

\FloatBarrier

<!-- Chapter 3 -->
\chapter{ Results}

Don't stop now.

```{r}
knitr::kable(data.frame('things I am about' = c('dogs', 'cats', 'ice cream'),
                        'mean of things' = rnorm(3)),
             caption = 'Fun things are really something!')
```

\FloatBarrier

<!-- Chapter 4 -->
\chapter{ Discussion}

Keep it going.

 
